### ISSUE TITLE
git clone command in readme is incorrect

### ISSUE THREAD

**Issue by imbev** [heusalagroup/hghs#30]
The readme says to execute the following:

```sh
git clone git@github.com:hangovergames/hghs.git hghs
```

This results in an error:

```ssh
ERROR: Repository not found.
fatal: Could not read from remote repository.
```

I was able to work around this by executing the following:

```sh
git  clone https://github.com/heusalagroup/hghs.git hghs
```

**Comment by thejhh** [comment]
Good catch! Thank you :)

Hangover Games was our old name -- actually it is still our alternative business name for gaming related stuff.
